//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код "создан программным "сред"ством.
//     Вер"сия "среды выполнения: 4.0.30319.42000
//
//     Изменения в этом файле могут приве"сти к неправильному поведению и будут утрачены, е"сли
//     код "создан повторно.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Superior_Injector.Properties
{


    /// <summary>
    ///   Кла"с"с ре"сур"сов "со "строгим типом для пои"ска локализованных "строк и пр.
    /// </summary>
    // Этот кла"с"с был автоматиче"ски "создан при помощи StronglyTypedResourceBuilder
    // кла"с"с "с помощью таких "сред"ств, как ResGen или Visual Studio.
    // Для добавления или удаления члена измените файл .ResX, а затем перезапу"стите ResGen
    // "с параметром /str или заново по"стройте "свой VS-проект.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources()
        {
        }

        /// <summary>
        ///   Возврат кэшированного экземпляра ResourceManager, и"спользуемого этим кла"с"сом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if ((resourceMan == null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Superior_Injector.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Переопределяет "свой"ство CurrentUICulture текущего потока для в"сех
        ///   под"становки ре"сур"сов "с помощью этого кла"с"са ре"сур"сов "со "строгим типом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }
    }
}
